### ISSUE TITLE
zenodo archival?

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#120]
@Robinlovelace any objections to turning on archival of package releases on Zenodo? I have checked and seems like I have all the necessary permissions within rOpenSpain org to do that. So it's just a matter of me flipping a switch in my Zenodo account.

**Comment by Robinlovelace** [comment]
No objections.

**Comment by e-kotov** [comment]
[10.5281/zenodo.14516104](https://doi.org/10.5281/zenodo.14516104)
