### ISSUE TITLE
improve type safety with rlang or assertthat or checkmate

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#23]
Improve type safety of the package
- either use assertthat https://github.com/hadley/assertthat
- or rlang (details here https://josiahparry.com/posts/2024-06-30-type-safety/)

**Comment by Robinlovelace** [comment]
{checkmate} is another option, mild preference for {rlang} as it's already an import. Simple is good.

**Comment by e-kotov** [comment]
The `{rlang}` option is problematic, it is more of a hack right now and will (may) be superseded by a separate package: https://github.com/tidyverse/design/issues/160 .

Therefore, I will either use `{checkmate}`, as it is still actively maintained, or will simply do with our internal check functions, as we have a lot of argument normalisation functions anyway.

**Comment by Robinlovelace** [comment]
Sounds good, simple good, and it is possible to over-engineer (and over-think) such things, `stopifnot()` also an option..
