### ISSUE TITLE
promote package and data during this year's #30DayMapChallenge?

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#36]

**Comment by Robinlovelace** [comment]
Great idea!

**Comment by Robinlovelace** [comment]
Heads-up @e-kotov and @eugenividal I've drafted this social media post and have scheduled it to go live today. No mention of 30 day map challenge, let's promote it with that hashtag too 🚀 

> {spanishoddata} is a new and in-progress #rstats package for importing large origin-destination (OD) datasets released by the Spanish Ministry of Transport by Egor Kotov, me + growing #opensource community. Thanks Eugeni Vidal-Tortosa for improved docs it's ready to share, feedback welcome 🙏 https://buff.ly/4fN4vsO

**Comment by e-kotov** [comment]
Let's perhaps wait for the branch I'm working on with clean and well working functions? I should be done today or tomorrow at the latest

**Comment by Robinlovelace** [comment]
Sure, will schedule for Friday afternoon, good motivation!

**Comment by Robinlovelace** [comment]
Scheduled for 15:00 tomorrow 🚀

**Comment by e-kotov** [comment]
> Scheduled for 15:00 tomorrow 🚀

Hard deadlines)

**Comment by Robinlovelace** [comment]
Ready to review PRs when you are.

**Comment by Robinlovelace** [comment]
Do you want me to postpone until Monday or Tuesday next week? I'm on childcare duties so will have limited time to review. I was thinking tomorrow afternoon based on this:

>  I should be done today or tomorrow at the latest

Happy to wait until ready.

**Comment by Robinlovelace** [comment]
Rescheduled for Tuesday 27th at 3pm UK time now.

![image](https://github.com/user-attachments/assets/48d936f1-a789-4ab0-9fcc-95ed8b998d88)

**Comment by e-kotov** [comment]
> thinking tomorrow

Aiming for that, but I don't think it will hurt if we postpone the post even till early next week, will give us plenty of time to test and discuss.

**Comment by e-kotov** [comment]
@Robinlovelace LinkedIn autopost failed?

**Comment by Robinlovelace** [comment]
> @Robinlovelace LinkedIn autopost failed?

It does sometimes, will check.

**Comment by Robinlovelace** [comment]
Sorted. Let me know when you want me to boost any additional comms on this!

**Comment by e-kotov** [comment]
> you want me to boost any additional comms on this!

Tbh, next time, tagging by twitter handle or name (on LinkedIn) would be better for networking.

**Comment by Robinlovelace** [comment]
Agreed! Post duplication service Buffer makes tagging hard, so I may put these out without Buffer next time.

**Comment by Robinlovelace** [comment]
Happy to be tagged and repost.

**Comment by e-kotov** [comment]
Sort of done, but I could not keep up. Some code can be found here: https://github.com/e-kotov/2024-30DayMapChallenge
