### ISSUE TITLE
Increase consitency between v1-2020-2021-mitma-data-codebook vignette and README

### ISSUE THREAD

**Issue by eugenividal** [rOpenSpain/spanishoddata#54]
There are some inconsistencies between the v1-2020-2021-mitma-data-codebook vignette and the README file. They are in 1) datasets' names, 2) headings' names and 3) (perhaps also) in the type of OD plots used. Increasing consistency on these aspects will help comprehension.

**Comment by e-kotov** [comment]
@eugenividal would you say we can close this now?

**Comment by Robinlovelace** [comment]
I think they are pretty consistent, so taking the initiative and closing. We can always reopen this one.

**Comment by eugenividal** [comment]
@e-kotov I agree with @Robinlovelace, the whole set seems more consistent. We can always bear it in mind when the whole thing is finished and reopen it if necessary.
