### ISSUE TITLE
stop piling up of XML files with file links?

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#64]
XML files with download links that are created once a day whenever `spod_get` or almost any other function is used are piling up in the `SPANISH_OD_DATA_DIR`. We need a good mechanism to get rid of them... On one hand, there are not that many of them and compared to the data itself, they are not taking up space, but do we really need old XML files...? We need a good solution.

One thing I am considering, is to at least create a dedicated folder for them, instead of dumping them in the root of `SPANISH_OD_DATA_DIR`.

@Robinlovelace suggestions? (not urgent)

**Comment by Robinlovelace** [comment]
:+1: to dedicated folder although not a big issue as you say.
