### ISSUE TITLE
tidy up code

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#88]
Mainly, improve maintainability of the code by moving functions that over time accumulated in single  .R files into separate files.

Do it in a separate PR that's dedicated to just that, once other issues in the "first stable release" milestone are completed.

**Comment by Robinlovelace** [comment]
Agreed, good practices will help maintainability. Code quality is already pretty good!

**Comment by e-kotov** [comment]
closed by #113
