### ISSUE TITLE
use cases vignette

### ISSUE THREAD

**Issue by e-kotov** [rOpenSpain/spanishoddata#93]
@Robinlovelace do we want to update/review/rename/repurpose/extend the https://ropenspain.github.io/spanishoddata/articles/uses.html vignette before the first release?

**Comment by Robinlovelace** [comment]
I don't see any major issues with it, see it as more of a placeholder for us to add more use cases as they appear, with links to other stuff. Seeing as the package is quite new and not out there yet there are not loads of use cases which is unsurprising.

**Comment by Robinlovelace** [comment]
Open to ideas though so, turning this around, does anyone else have suggested changes to it?

**Comment by Robinlovelace** [comment]
👍 to both suggestions, move to an article and state that it's about geo disaggregation of the od data, that could be useful for many use cases.
